import { chromium } from 'playwright';
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || undefined });
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 2 });
await page.goto('http://localhost:4173/?seed=showcase-42'); await page.waitForSelector('.map-canvas', { timeout: 20000 }); await page.waitForTimeout(2500);
if (await page.locator('text=Got it').count()) await page.click('text=Got it');
await page.click('.clock .speeds button:nth-child(5)'); await page.waitForTimeout(6000); await page.click('.clock .speeds button:nth-child(1)');
if (await page.locator('.cinematic').count()) await page.click('.cinematic');
await page.click('.bottom-nav button[aria-label="More"]'); await page.click('.modal button:has-text("History")'); await page.waitForTimeout(300);
await page.click('.chip:has-text("Sagas")'); await page.waitForTimeout(400);
await page.screenshot({ path: 'tests/e2e/output/review-sagas-mobile.png' }); await browser.close();
