/**
 * God Mode presets: structured interventions the player can trigger directly.
 * Every preset resolves to one or more events with causedBy = 'player'.
 */
import { RNG } from '../rng';
import type { World, WorldEvent, Country, Sector, GovernmentType, Profession, ID } from '../types';
import { SECTORS } from '../types';
import * as A from '../events/actions';
import { createEvent, fx, ref } from '../events/engine';
import { relate } from '../simulation/relations';
import { yearOf } from '../time';
import { holdFestival, holdFair } from '../simulation/calendar';
import { regionsOf } from '../generator/regions';
import type { Region } from '../types';

/** Resolve a region param: an id, or a name typed into the preset form; must belong to the country. */
const regionParam = (w: World, country: Country, v?: string): Region | undefined => { if (!v) return undefined; const q = v.trim().toLowerCase(); return regionsOf(w, country).find((r) => r.id === v || r.name.toLowerCase() === q) ?? regionsOf(w, country).find((r) => r.name.toLowerCase().includes(q)); };

export type ParamType = 'country' | 'country2' | 'company' | 'person' | 'person2' | 'sector' | 'government' | 'text' | 'choice' | 'profession';
export interface PresetParam { key: string; type: ParamType; label: string; options?: { value: string; label: string }[]; optional?: boolean; }
export interface GodPreset {
  id: string;
  label: string;
  icon: string;
  group: 'conflict' | 'politics' | 'economy' | 'science' | 'disaster' | 'society' | 'people';
  description: string;
  severity: 1 | 2 | 3 | 4 | 5;
  params: PresetParam[];
  run: (world: World, rng: RNG, p: Record<string, string>) => WorldEvent | null;
}

const c = (w: World, id?: string, rng?: RNG): Country => (id && w.countries[id]) || (rng ? rng.pick(Object.values(w.countries)) : Object.values(w.countries)[0]);
const other = (w: World, a: Country, id?: string, rng?: RNG): Country => (id && id !== a.id && w.countries[id]) || (rng ? rng.pick(Object.values(w.countries).filter((x) => x.id !== a.id)) : Object.values(w.countries).find((x) => x.id !== a.id)!);
const P = 'player' as const;
const GOVS: GovernmentType[] = ['democracy', 'republic', 'monarchy', 'technocracy', 'autocracy', 'military-junta', 'theocracy', 'federation', 'oligarchy', 'council'];
const PROFS: Profession[] = ['politician', 'scientist', 'journalist', 'entrepreneur', 'activist', 'general', 'celebrity', 'criminal', 'artist', 'executive', 'diplomat', 'athlete', 'engineer', 'religious-leader'];

export const GOD_PRESETS: GodPreset[] = [
  // Conflict
  { id: 'start-war', label: 'Start War', icon: '⚔', group: 'conflict', severity: 5, description: 'Force one nation to declare war on another.', params: [{ key: 'a', type: 'country', label: 'Aggressor' }, { key: 'b', type: 'country2', label: 'Target' }], run: (w, r, p) => { const a = c(w, p.a, r); return A.declareWar(w, r, a, other(w, a, p.b, r), P, true); } },
  { id: 'end-war', label: 'End War', icon: '🕊', group: 'conflict', severity: 4, description: 'Impose a ceasefire on an active war.', params: [{ key: 'a', type: 'country', label: 'Country' }], run: (w, r, p) => { const a = c(w, p.a, r); const b = a.atWarWith[0] ? w.countries[a.atWarWith[0]] : undefined; if (!b) { const any = Object.values(w.countries).find((x) => x.atWarWith.length); if (!any) return null; return A.endWar(w, r, any, w.countries[any.atWarWith[0]], P, true, 'stalemate'); } return A.endWar(w, r, a, b, P, true, 'stalemate'); } },
  { id: 'increase-tension', label: 'Increase Tension', icon: '🔥', group: 'conflict', severity: 3, description: 'Poison relations between two countries.', params: [{ key: 'a', type: 'country', label: 'Country' }, { key: 'b', type: 'country2', label: 'Rival' }], run: (w, r, p) => { const a = c(w, p.a, r); return A.shiftTension(w, r, a, other(w, a, p.b, r), 40, P, true, 'A mysterious provocation'); } },
  { id: 'reduce-tension', label: 'Reduce Tension', icon: '🤝', group: 'conflict', severity: 2, description: 'Ease hostility between two countries.', params: [{ key: 'a', type: 'country', label: 'Country' }, { key: 'b', type: 'country2', label: 'Other' }], run: (w, r, p) => { const a = c(w, p.a, r); return A.shiftTension(w, r, a, other(w, a, p.b, r), -40, P, true, 'An unexpected act of goodwill'); } },
  { id: 'alliance', label: 'Forge Alliance', icon: '🛡', group: 'conflict', severity: 3, description: 'Bind two nations in a defense pact.', params: [{ key: 'a', type: 'country', label: 'Country' }, { key: 'b', type: 'country2', label: 'Partner' }], run: (w, r, p) => { const a = c(w, p.a, r); return A.formAlliance(w, r, a, other(w, a, p.b, r), P, true); } },
  { id: 'break-alliance', label: 'Diplomatic Breakdown', icon: '💥', group: 'conflict', severity: 3, description: 'Shatter an existing alliance.', params: [{ key: 'a', type: 'country', label: 'Country' }], run: (w, r, p) => { const a = c(w, p.a, r); const b = a.alliances[0] ? w.countries[a.alliances[0]] : null; if (!b) return A.shiftTension(w, r, a, other(w, a, undefined, r), 50, P, true, 'A diplomatic rupture'); return A.breakAlliance(w, r, a, b, P, true); } },
  { id: 'destabilize', label: 'Destabilize Region', icon: '🌪', group: 'conflict', severity: 4, description: 'Unrest and suspicion spread across a country and its neighbors.', params: [{ key: 'a', type: 'country', label: 'Epicenter' }], run: (w, r, p) => { const a = c(w, p.a, r); const all = [a, ...a.neighbors.map((n) => w.countries[n]).filter(Boolean)]; for (const n of a.neighbors) A.setRelation(w, a, w.countries[n], -25); return createEvent(w, { category: 'political', type: 'region.destabilized', severity: 4, causedBy: P, playerIntervention: true, title: `Wave of instability sweeps ${a.name} and its neighbors`, description: `Bombings, strikes and disinformation campaigns erupted simultaneously across ${all.map((x) => x.name).join(', ')}. Intelligence agencies suspect an unseen hand.`, location: { countryId: a.id }, actors: all.map((x) => ref('country', x.id)), effects: all.flatMap((x) => [fx('country', x.id, 'stability', x.id === a.id ? -25 : -10), fx('country', x.id, 'unrest', x.id === a.id ? 25 : 10)]), tags: ['instability', a.code], historic: true }); } },
  // Politics
  { id: 'change-government', label: 'Change Government', icon: '🏛', group: 'politics', severity: 4, description: 'Rewrite a nation\'s constitution overnight.', params: [{ key: 'a', type: 'country', label: 'Country' }, { key: 'gov', type: 'government', label: 'New system', options: GOVS.map((g) => ({ value: g, label: g })) }], run: (w, r, p) => A.changeGovernment(w, r, c(w, p.a, r), (GOVS.includes(p.gov as GovernmentType) ? p.gov : r.pick(GOVS)) as GovernmentType, P, true) },
  { id: 'collapse-government', label: 'Collapse Government', icon: '🏚', group: 'politics', severity: 5, description: 'The state ceases to function.', params: [{ key: 'a', type: 'country', label: 'Country' }], run: (w, r, p) => A.collapseGovernment(w, r, c(w, p.a, r), P, true) },
  { id: 'revolution', label: 'Trigger Revolution', icon: '✊', group: 'politics', severity: 5, description: 'The people rise and topple their rulers.', params: [{ key: 'a', type: 'country', label: 'Country' }], run: (w, r, p) => A.changeLeader(w, r, c(w, p.a, r), 'revolution', P, true) },
  { id: 'coup', label: 'Military Coup', icon: '🎖', group: 'politics', severity: 5, description: 'Generals seize the capital.', params: [{ key: 'a', type: 'country', label: 'Country' }], run: (w, r, p) => A.changeLeader(w, r, c(w, p.a, r), 'coup', P, true) },
  { id: 'create-country', label: 'Create Country', icon: '🗺', group: 'politics', severity: 5, description: 'Carve a new nation out of an existing one.', params: [{ key: 'a', type: 'country', label: 'Parent country' }, { key: 'region', type: 'text', label: 'Region to split off (optional, by name)', optional: true }, { key: 'name', type: 'text', label: 'Name (optional)', optional: true }], run: (w, r, p) => { const parent = c(w, p.a, r); const region = regionParam(w, parent, p.region); if (region) { const ev = A.createCountry(w, r, parent, P, true, p.name?.trim() || undefined, region.id); if (ev) return ev; } const ev = A.createCountry(w, r, parent, P, true, p.name?.trim() || undefined); if (ev) return ev; const alt = Object.values(w.countries).filter((x) => x.cityIds.length >= 2 && x.area > 30); for (const x of alt) { const e = A.createCountry(w, r, x, P, true, p.name?.trim() || undefined); if (e) return e; } return null; } },
  { id: 'movement', label: 'Create Movement', icon: '📣', group: 'politics', severity: 2, description: 'A new political movement is born.', params: [{ key: 'a', type: 'country', label: 'Country' }, { key: 'name', type: 'text', label: 'Name (optional)', optional: true }], run: (w, r, p) => A.createMovement(w, r, c(w, p.a, r), P, true, undefined, p.name?.trim() || undefined) },
  { id: 'opinion-up', label: 'Rally Public Opinion', icon: '📈', group: 'politics', severity: 2, description: 'The public swings behind the government.', params: [{ key: 'a', type: 'country', label: 'Country' }], run: (w, r, p) => A.shiftOpinion(w, r, c(w, p.a, r), 25, P, true, 'An inexplicable surge of optimism') },
  { id: 'opinion-down', label: 'Turn Public Opinion', icon: '📉', group: 'politics', severity: 2, description: 'The public turns against its leaders.', params: [{ key: 'a', type: 'country', label: 'Country' }], run: (w, r, p) => A.shiftOpinion(w, r, c(w, p.a, r), -25, P, true, 'A sudden collapse of trust') },
  // Economy
  { id: 'create-company', label: 'Create Company', icon: '🏢', group: 'economy', severity: 1, description: 'Found a new company.', params: [{ key: 'a', type: 'country', label: 'Country' }, { key: 'sector', type: 'sector', label: 'Sector', options: SECTORS.map((s) => ({ value: s, label: s })) }, { key: 'name', type: 'text', label: 'Name (optional)', optional: true }], run: (w, r, p) => A.foundCompany(w, r, c(w, p.a, r), (SECTORS.includes(p.sector as Sector) ? p.sector : r.pick(SECTORS)) as Sector, P, true, undefined, p.name?.trim() || undefined) },
  { id: 'bankrupt', label: 'Bankrupt Company', icon: '📉', group: 'economy', severity: 3, description: 'A company collapses overnight.', params: [{ key: 'co', type: 'company', label: 'Company' }], run: (w, r, p) => { const co = w.companies[p.co] ?? r.pickWeighted(Object.values(w.companies).filter((x) => x.alive), (x) => x.value); return A.bankruptCompany(w, r, co, P, true, 'In a collapse nobody can explain'); } },
  { id: 'boom', label: 'Economic Boom', icon: '🚀', group: 'economy', severity: 3, description: 'Prosperity floods a nation.', params: [{ key: 'a', type: 'country', label: 'Country (blank = world)', optional: true }], run: (w, r, p) => A.economicShock(w, r, p.a ? c(w, p.a) : null, 'boom', P, true) },
  { id: 'crisis', label: 'Economic Crisis', icon: '🏦', group: 'economy', severity: 4, description: 'Credit dries up, jobs vanish.', params: [{ key: 'a', type: 'country', label: 'Country (blank = world)', optional: true }], run: (w, r, p) => A.economicShock(w, r, p.a ? c(w, p.a) : null, 'crisis', P, true) },
  { id: 'crash', label: 'Market Crash', icon: '💣', group: 'economy', severity: 4, description: 'Markets go into free fall.', params: [{ key: 'a', type: 'country', label: 'Country (blank = global)', optional: true }], run: (w, r, p) => A.economicShock(w, r, p.a ? c(w, p.a) : null, 'crash', P, true) },
  { id: 'famine', label: 'Famine', icon: '🌾', group: 'economy', severity: 4, description: 'Harvests fail; grain prices spiral and the poor go hungry.', params: [{ key: 'a', type: 'country', label: 'Worst-hit country (blank = poorest)', optional: true }], run: (w, r, p) => { const g = w.commodities.grain; const cs = Object.values(w.countries); const target = p.a ? c(w, p.a) : cs.slice().sort((x, y) => (x.gdp / x.population) - (y.gdp / y.population))[0]; if (g) { g.price *= 1.45; g.history.push(g.price); } return createEvent(w, { category: 'environmental', type: 'harvest.failure', severity: 4, causedBy: P, playerIntervention: true, title: `Harvests fail across ${target.name} and beyond`, description: `${r.pick(['Blight', 'A season without rain', 'Locusts', 'Floods at planting time'])} wiped out the harvest in ${target.name} and its neighbours. Grain jumped to ${g ? g.price.toFixed(0) + ' ' + g.unit : 'record highs'} overnight; the poorest nations will feel it first.`, location: { countryId: target.id }, actors: [ref('country', target.id)], effects: [fx('country', target.id, 'happiness', -8), fx('country', target.id, 'unrest', 6), fx('country', target.id, 'gdpGrowth', -1.5)], tags: ['famine', 'food', target.code], historic: true, data: { shocks: [{ commodityId: 'grain', pct: 0.1 }, { sector: 'agriculture', pct: 0.06 }] } }); } },
  { id: 'rains', label: 'Rains Return', icon: '🌧', group: 'disaster', severity: 2, description: 'Break a drought: rain lifts water reserves and eases grain prices.', params: [{ key: 'a', type: 'country', label: 'Country (blank = driest)' }], run: (w, r, p) => { const cs = Object.values(w.countries); const target = p.a ? c(w, p.a) : cs.slice().sort((x, y) => (x.resources.water ?? 50) - (y.resources.water ?? 50))[0]; target.resources.water = Math.min(100, (target.resources.water ?? 50) + 12); const drought = w.events.slice(-800).find((e) => e.type === 'disaster.drought' && e.location.countryId === target.id && w.day - e.day <= 60 && !e.data?.ended); if (drought) { drought.data = { ...(drought.data ?? {}), ended: w.day }; } return createEvent(w, { category: 'environmental', type: 'rains', severity: 2, causedBy: P, playerIntervention: true, title: `The rains return to ${target.name}`, description: `After ${drought ? 'a drought that emptied reservoirs' : 'a long dry spell'}, ${r.pick(['a week of steady rain', 'monsoon clouds', 'the first storms in months'])} soaked ${target.name}. ${r.pick(['Farmers wept in the fields.', 'Rivers ran again by morning.', 'Grain futures fell on the news.'])}`, location: { countryId: target.id }, actors: [ref('country', target.id)], effects: [fx('country', target.id, 'happiness', 4), fx('country', target.id, 'unrest', -2), fx('country', target.id, 'gdpGrowth', 0.5)], tags: ['weather', 'rain', target.code], data: { shocks: [{ commodityId: 'grain', pct: -0.04 }] } }); } },
  { id: 'export-ban', label: 'Grain Export Ban', icon: '🚫', group: 'economy', severity: 3, description: 'A breadbasket nation stops exporting grain.', params: [{ key: 'a', type: 'country', label: 'Exporter (blank = biggest farmland)' }], run: (w, r, p) => { const cs = Object.values(w.countries); const target = p.a ? c(w, p.a) : cs.slice().sort((x, y) => (y.resources.farmland ?? 50) - (x.resources.farmland ?? 50))[0]; return A.grainExportBan(w, r, target, P, true); } },
  { id: 'energy-crisis', label: 'Energy Crisis', icon: '⚡', group: 'economy', severity: 4, description: 'Fuel and power become scarce.', params: [{ key: 'a', type: 'country', label: 'Country (blank = world)', optional: true }], run: (w, r, p) => A.economicShock(w, r, p.a ? c(w, p.a) : null, 'energy-crisis', P, true) },
  { id: 'resource', label: 'Resource Discovery', icon: '⛏', group: 'economy', severity: 3, description: 'Vast reserves are found.', params: [{ key: 'a', type: 'country', label: 'Country' }, { key: 'res', type: 'choice', label: 'Resource', options: ['oil', 'minerals', 'rareEarth', 'water', 'farmland'].map((v) => ({ value: v, label: v })) }], run: (w, r, p) => A.resourceDiscovery(w, r, c(w, p.a, r), p.res || 'oil', P, true) },
  // Science
  { id: 'breakthrough', label: 'Tech Breakthrough', icon: '🔬', group: 'science', severity: 4, description: 'A technology leaps a generation ahead.', params: [{ key: 'co', type: 'company', label: 'Company (optional)', optional: true }, { key: 'a', type: 'country', label: 'Country', optional: true }, { key: 'field', type: 'text', label: 'Field (e.g. battery, fusion)', optional: true }], run: (w, r, p) => { const co = w.companies[p.co] ?? null; const country = co ? w.countries[co.countryId] : c(w, p.a, r); return A.techBreakthrough(w, r, co, country, p.field?.trim() || r.pick(['fusion', 'battery', 'quantum computing', 'gene editing', 'artificial intelligence']), P, true, 1.5); } },
  { id: 'discovery', label: 'Scientific Discovery', icon: '🧪', group: 'science', severity: 4, description: 'Science reveals something new about reality.', params: [{ key: 'a', type: 'country', label: 'Country' }, { key: 'what', type: 'text', label: 'Discovery (optional)', optional: true }], run: (w, r, p) => { const country = c(w, p.a, r); const sci = A.peopleOf(w, country.id, 'scientist')[0]; const what = p.what?.trim() || r.pick(['life on another world', 'a cure for a major disease', 'a room-temperature superconductor', 'proof of extra dimensions']); return createEvent(w, { category: 'scientific', type: 'discovery', severity: 4, causedBy: P, playerIntervention: true, title: `${country.adjective} scientists announce ${what}`, description: `In a discovery that will define the century, researchers in ${country.name}${sci ? ` led by ${sci.name}` : ''} confirmed ${what}. The scientific world is in uproar.`, location: { countryId: country.id }, actors: [ref('country', country.id), ...(sci ? [ref('person', sci.id)] : [])], effects: [fx('country', country.id, 'technology', 5), ...(sci ? [fx('person', sci.id, 'fame', 40), fx('person', sci.id, 'influence', 20)] : [])], tags: ['science', 'discovery', country.code], historic: true, data: { field: what } }); } },
  { id: 'accelerate-tech', label: 'Accelerate Progress', icon: '⏩', group: 'science', severity: 3, description: 'Technological progress surges worldwide.', params: [], run: (w, r) => { for (const x of Object.values(w.countries)) x.technology = Math.min(100, x.technology + 6); return createEvent(w, { category: 'technological', type: 'tech.acceleration', severity: 4, causedBy: P, playerIntervention: true, title: 'A golden age of invention begins', description: 'Laboratories across the world report breakthroughs at an unprecedented pace. Something has changed in the collective mind of humanity.', actors: [], effects: [], tags: ['technology', 'global'], historic: true, data: { shocks: [{ sector: 'technology', pct: 0.1 }, { sector: 'biotech', pct: 0.08 }] } }); } },
  // Disasters
  { id: 'disaster', label: 'Natural Disaster', icon: '🌊', group: 'disaster', severity: 4, description: 'The earth strikes back.', params: [{ key: 'a', type: 'country', label: 'Country' }, { key: 'kind', type: 'choice', label: 'Type', options: ['earthquake', 'flood', 'hurricane', 'drought', 'wildfire', 'volcano', 'tsunami'].map((v) => ({ value: v, label: v })) }], run: (w, r, p) => A.disaster(w, r, c(w, p.a, r), (p.kind || 'earthquake') as 'earthquake', P, true, 1.5) },
  { id: 'meteor', label: 'Meteor Strike', icon: '☄', group: 'disaster', severity: 5, description: 'A rock from the sky.', params: [{ key: 'a', type: 'country', label: 'Country' }], run: (w, r, p) => A.disaster(w, r, c(w, p.a, r), 'meteor', P, true, 2.5) },
  { id: 'epidemic', label: 'Epidemic', icon: '🦠', group: 'disaster', severity: 3, description: 'A new pathogen emerges.', params: [{ key: 'a', type: 'country', label: 'Country' }], run: (w, r, p) => A.epidemic(w, r, c(w, p.a, r), P, true, false) },
  { id: 'pandemic', label: 'Global Pandemic', icon: '🌐', group: 'disaster', severity: 5, description: 'The whole world falls ill.', params: [{ key: 'a', type: 'country', label: 'Origin' }], run: (w, r, p) => A.epidemic(w, r, c(w, p.a, r), P, true, true) },
  // Society
  { id: 'migration', label: 'Migration Wave', icon: '🧭', group: 'society', severity: 3, description: 'Millions move.', params: [{ key: 'a', type: 'country', label: 'From' }, { key: 'b', type: 'country2', label: 'To' }], run: (w, r, p) => { const a = c(w, p.a, r); return A.migrationWave(w, r, a, other(w, a, p.b, r), a.population * 0.04, P, true); } },
  { id: 'religion', label: 'Create Belief Movement', icon: '🕯', group: 'society', severity: 2, description: 'A new faith takes root.', params: [{ key: 'a', type: 'country', label: 'Country' }, { key: 'name', type: 'text', label: 'Name (optional)', optional: true }], run: (w, r, p) => A.createReligion(w, r, c(w, p.a, r), P, true, p.name?.trim() || undefined) },
  // People
  { id: 'figure', label: 'Create Public Figure', icon: '🌟', group: 'people', severity: 2, description: 'Someone new steps into the spotlight.', params: [{ key: 'a', type: 'country', label: 'Country' }, { key: 'prof', type: 'profession', label: 'Profession', options: PROFS.map((v) => ({ value: v, label: v })) }, { key: 'name', type: 'text', label: 'Name (optional)', optional: true }], run: (w, r, p) => A.createPublicFigure(w, r, c(w, p.a, r), (PROFS.includes(p.prof as Profession) ? p.prof : 'entrepreneur') as Profession, P, true, p.name?.trim() || undefined) },
  { id: 'remove-figure', label: 'Remove Public Figure', icon: '🪦', group: 'people', severity: 3, description: 'Someone vanishes from history.', params: [{ key: 'p', type: 'person', label: 'Person' }, { key: 'how', type: 'choice', label: 'How', options: ['disappearance', 'accident', 'assassination', 'natural'].map((v) => ({ value: v, label: v })) }], run: (w, r, p) => { const person = w.people[p.p] ?? r.pickWeighted(Object.values(w.people).filter((x) => x.alive), (x) => x.fame); return A.killPerson(w, r, person, (p.how || 'disappearance') as 'disappearance', P, true); } },
  { id: 'scandal', label: 'Trigger Scandal', icon: '📰', group: 'people', severity: 3, description: 'Skeletons fall out of the closet.', params: [{ key: 'p', type: 'person', label: 'Person' }, { key: 'what', type: 'text', label: 'What (optional)', optional: true }], run: (w, r, p) => { const person = w.people[p.p] ?? r.pickWeighted(Object.values(w.people).filter((x) => x.alive && x.fame > 20), (x) => x.fame); return A.scandal(w, r, person, P, true, p.what?.trim() || undefined); } },
  { id: 'reveal-secret', label: 'Reveal Secret', icon: '🔓', group: 'people', severity: 3, description: 'A hidden truth about a leader becomes public.', params: [{ key: 'a', type: 'country', label: 'Country' }], run: (w, r, p) => { const country = c(w, p.a, r); const leader = w.people[country.leaderId]; if (!leader) return null; return A.scandal(w, r, leader, P, true, r.pick(['a secret deal with a hostile power', 'a hidden fortune abroad', 'orders to spy on citizens', 'a covered-up health crisis', 'a faked biography'])); } },
  { id: 'annex', label: 'Annex Region', icon: '🚩', group: 'conflict', severity: 4, description: 'Redraw the map: one nation takes a region from a neighbour (the nearest one if none is named).', params: [{ key: 'a', type: 'country', label: 'Annexing nation' }, { key: 'b', type: 'country2', label: 'Victim (blank = a neighbour)', optional: true }, { key: 'region', type: 'text', label: 'Region (optional, by name)', optional: true }], run: (w, r, p) => { const a = c(w, p.a, r); const candidates = (p.b && w.countries[p.b] && p.b !== a.id ? [w.countries[p.b]] : a.neighbors.map((id) => w.countries[id]).filter(Boolean)).filter((v) => (v.regionIds ?? []).length >= 2); if (!candidates.length) return null; for (const v of candidates) { const region = regionParam(w, v, p.region) ?? regionsOf(w, v).filter((x) => !x.cityIds.includes(v.capitalId)).sort((x, y) => y.unrest - x.unrest)[0]; if (!region) continue; const ev = A.transferRegion(w, r, region, a, P, true, `${a.name} marched into ${region.name} and declared it ${a.adjective} soil`); if (ev) return ev; } return null; } },
  { id: 'referendum', label: 'Regional Referendum', icon: '🗳', group: 'politics', severity: 3, description: 'Let a region vote on its status — the most restless one if none is named. The result follows weeks later.', params: [{ key: 'a', type: 'country', label: 'Country' }, { key: 'region', type: 'text', label: 'Region (optional, by name)', optional: true }], run: (w, r, p) => { const a = c(w, p.a, r); const region = regionParam(w, a, p.region) ?? regionsOf(w, a).filter((x) => !x.cityIds.includes(a.capitalId)).sort((x, y) => y.unrest - x.unrest)[0]; if (!region) return null; region.history.push({ day: w.day, text: 'Referendum called.' }); const anchor = w.cities[region.cityIds[0]]; const gov = region.governorId ? w.people[region.governorId] : undefined; return createEvent(w, { category: 'political', type: 'region.referendum', severity: 3, causedBy: P, playerIntervention: true, title: `${a.name} calls a referendum in ${region.name}`, description: `By decree, ${region.name} will vote on its own status within weeks. ${gov ? `Governor ${gov.name} ${/autonomy|independence|free/i.test(gov.objective) ? 'is campaigning for self-rule' : 'is campaigning to stay'}.` : 'Both camps are printing posters.'} ${r.pick(['Turnout will decide it.', 'The capital is confident. The capital is often confident.', 'Neighbours are watching nervously.'])}`, location: { countryId: a.id, cityId: anchor?.id, x: anchor?.x ?? a.centroid.x, y: anchor?.y ?? a.centroid.y }, actors: [ref('country', a.id), ...(gov ? [ref('person', gov.id)] : [])], effects: [fx('country', a.id, 'polarization', 3)], tags: ['region', 'referendum', a.code], data: { regionId: region.id, region: region.name, governorLed: false } }); } },
  { id: 'autonomy', label: 'Grant Autonomy', icon: '🏛', group: 'politics', severity: 2, description: 'Devolve power to a restless region — or, without one named, to the most aggrieved region in the country.', params: [{ key: 'a', type: 'country', label: 'Country' }, { key: 'region', type: 'text', label: 'Region (optional, by name)', optional: true }], run: (w, r, p) => { const a = c(w, p.a, r); const region = regionParam(w, a, p.region) ?? regionsOf(w, a).filter((x) => !x.cityIds.includes(a.capitalId)).sort((x, y) => y.unrest - x.unrest)[0]; if (!region) return null; region.autonomy = Math.min(100, region.autonomy + 30); region.unrest = Math.max(0, region.unrest - 25); region.history.push({ day: w.day, text: `Granted autonomy by decree.` }); const anchor = w.cities[region.cityIds[0]]; return createEvent(w, { category: 'political', type: 'region.concession', severity: 2, causedBy: P, playerIntervention: true, title: `${a.name} grants ${region.name} self-rule`, description: `By decree, ${region.name} gets its own assembly and control of its ${r.pick(['schools and language', 'tax revenue', 'policing', 'ports and roads'])}. ${r.pick(['Hardliners in the capital called it the beginning of the end.', 'The regional council met the same week.', 'Nationalists in the region said it was not enough.'])}`, location: { countryId: a.id, cityId: anchor?.id, x: anchor?.x ?? a.centroid.x, y: anchor?.y ?? a.centroid.y }, actors: [ref('country', a.id)], effects: [fx('country', a.id, 'stability', 2), fx('country', a.id, 'freedom', 1), fx('country', a.id, 'unrest', -2)], tags: ['region', 'autonomy', a.code], data: { regionId: region.id, region: region.name } }); } },
  { id: 'festival', label: 'Film Festival', icon: '🎬', group: 'society', severity: 2, description: 'Roll out a red carpet: a festival crowns an artist, and an unfree host may ban the winning film.', params: [{ key: 'a', type: 'country', label: 'Host (blank = the world picks)', optional: true }], run: (w, r, p) => holdFestival(w, r, { host: p.a ? c(w, p.a) : undefined, player: true }) },
  { id: 'trade-fair', label: 'Trade Fair', icon: '🏗', group: 'economy', severity: 2, description: 'A nation hosts its trading partners; relations warm and the headline companies may form a venture.', params: [{ key: 'a', type: 'country', label: 'Host (blank = biggest trader)', optional: true }], run: (w, r, p) => holdFair(w, r, { host: p.a ? c(w, p.a) : undefined, player: true }) },
  { id: 'election', label: 'Snap Election', icon: '🗳', group: 'politics', severity: 3, description: 'Force a country to the polls within weeks — even one that never votes.', params: [{ key: 'a', type: 'country', label: 'Country' }], run: (w, r, p) => { const a = c(w, p.a, r); const forced = !a.electionEvery; if (forced) { a.electionEvery = 5; } a.nextElectionYear = yearOf(w.day, w.meta.startYear); const leader = w.people[a.leaderId]; return createEvent(w, { category: 'political', type: 'election.called', severity: forced ? 4 : 3, causedBy: P, playerIntervention: true, title: forced ? `${a.name} to hold its first free election` : `${a.name} calls a snap election`, description: forced ? `In a stunning reversal, the government of ${a.name} announced open elections within weeks. ${leader ? `${leader.name} insists they will stand as a candidate.` : ''} Nobody is sure whether the vote will be honored.` : `${leader?.name ?? 'The government'} dissolved parliament and called an early vote${a.approval < 45 ? ', a gamble given dismal approval ratings' : ', hoping to cash in on strong approval'}. Campaigning begins immediately.`, location: { countryId: a.id }, actors: [ref('country', a.id), ...(leader ? [ref('person', leader.id)] : [])], effects: [fx('country', a.id, 'polarization', 6), fx('country', a.id, 'freedom', forced ? 12 : 0), fx('country', a.id, 'stability', -3)], tags: ['election', 'politics', a.code], historic: forced, data: { forced } }); } },
  { id: 'feud', label: 'Spark Rivalry', icon: '🥊', group: 'people', severity: 2, description: 'Turn two people into bitter rivals.', params: [{ key: 'p', type: 'person', label: 'Person' }, { key: 'p2', type: 'person2', label: 'Rival' }], run: (w, r, p) => { const alive = Object.values(w.people).filter((x) => x.alive && x.fame > 20); const a = w.people[p.p] ?? r.pickWeighted(alive, (x) => x.fame); let b = p.p2 && p.p2 !== a.id ? w.people[p.p2] : undefined; if (!b) { const same = alive.filter((x) => x.id !== a.id && (x.countryId === a.countryId || x.profession === a.profession)); b = r.pickWeighted(same.length ? same : alive.filter((x) => x.id !== a.id), (x) => x.fame + (x.profession === a.profession ? 30 : 0)); } a.relationships = a.relationships.filter((rel) => rel.target.id !== b!.id); b.relationships = b.relationships.filter((rel) => rel.target.id !== a.id); relate(w, a, b, 'rival', -0.7); const why = r.pick(['a contested credit for a shared success', 'a leaked private insult', 'a betrayal over a business deal', 'a very public snub', 'competing claims to the same legacy', 'an old debt never repaid']); a.history.push({ day: w.day, text: `Became a bitter rival of ${b.name}.` }); b.history.push({ day: w.day, text: `Became a bitter rival of ${a.name}.` }); return createEvent(w, { category: 'personal', type: 'feud', severity: a.fame > 60 && b.fame > 60 ? 3 : 2, causedBy: P, playerIntervention: true, title: `${a.name} and ${b.name} become sworn enemies`, description: `What began as ${why} has hardened into open hostility between ${a.name} and ${b.name}. ${r.pick(['Mutual friends have given up mediating.', 'Both camps are briefing against each other.', 'Neither will be in the same room as the other.'])}`, location: { cityId: a.cityId }, actors: [ref('person', a.id), ref('person', b.id)], effects: [fx('person', a.id, 'fame', 4), fx('person', b.id, 'fame', 4)], tags: ['feud', 'people', 'rivalry'] }); } },
  { id: 'romance', label: 'Matchmaker', icon: '💞', group: 'people', severity: 1, description: 'Two people fall in love.', params: [{ key: 'p', type: 'person', label: 'Person' }, { key: 'p2', type: 'person2', label: 'Partner' }], run: (w, r, p) => { const alive = Object.values(w.people).filter((x) => x.alive && x.fame > 15 && !x.relationships.some((rel) => rel.type === 'partner' && w.people[rel.target.id]?.alive)); const a = w.people[p.p] ?? r.pickWeighted(alive, (x) => x.fame); let b = p.p2 && p.p2 !== a.id ? w.people[p.p2] : undefined; if (!b) { const cands = alive.filter((x) => x.id !== a.id && Math.abs(x.birthDay - a.birthDay) < 15 * 365); b = r.pickWeighted(cands.length ? cands : alive.filter((x) => x.id !== a.id), (x) => x.fame + (x.countryId === a.countryId ? 30 : 0)); } for (const x of [a, b]) { x.relationships = x.relationships.filter((rel) => rel.type !== 'partner' && rel.target.id !== a.id && rel.target.id !== b!.id); } relate(w, a, b, 'partner', 0.9); a.history.push({ day: w.day, text: `Began a partnership with ${b.name}.` }); b.history.push({ day: w.day, text: `Began a partnership with ${a.name}.` }); const famous = a.fame > 55 || b.fame > 55; const cross = a.countryId !== b.countryId; return createEvent(w, { category: 'personal', type: 'partnership', severity: famous ? 2 : 1, causedBy: P, playerIntervention: true, title: `${a.name} and ${b.name} ${r.pick(['are in love', 'go public as a couple', 'announce their engagement'])}`, description: `${famous ? 'The gossip press is beside itself: ' : ''}${a.name} (${a.profession.replace('-', ' ')}) and ${b.name} (${b.profession.replace('-', ' ')}) ${cross ? `have become the world's most talked-about cross-border couple` : r.pick(['were photographed together at dawn', 'confirmed the rumors', 'made it official'])}.`, location: { cityId: a.cityId }, actors: [ref('person', a.id), ref('person', b.id)], effects: [fx('person', a.id, 'fame', famous ? 5 : 2), fx('person', b.id, 'fame', famous ? 5 : 2)], tags: ['personal', 'love'] }); } },
];

export function presetById(id: string): GodPreset | undefined { return GOD_PRESETS.find((p) => p.id === id); }
export const GOD_GROUPS: { id: GodPreset['group']; label: string }[] = [
  { id: 'conflict', label: 'Conflict & Diplomacy' }, { id: 'politics', label: 'Politics' }, { id: 'economy', label: 'Economy' }, { id: 'science', label: 'Science & Tech' }, { id: 'disaster', label: 'Disasters' }, { id: 'society', label: 'Society' }, { id: 'people', label: 'People' },
];
export type { ID };
